# Generated by Django 3.2.8 on 2021-11-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20211101_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('Name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('SteelMill', models.PositiveIntegerField(default=0)),
                ('HCollector', models.PositiveIntegerField(default=0)),
                ('ParticleCollider', models.PositiveIntegerField(default=0)),
                ('ShipFactory', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('Name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('Fighter', models.PositiveIntegerField(default=0)),
                ('HeavyFighter', models.PositiveIntegerField(default=0)),
                ('Destroyer', models.PositiveIntegerField(default=0)),
                ('Corvette', models.PositiveIntegerField(default=0)),
                ('Cruiser', models.PositiveIntegerField(default=0)),
                ('Battleship', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
