# Generated by Django 3.2.8 on 2021-11-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_buildings_fleet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buildings',
            new_name='Building',
        ),
    ]
