# Generated by Django 3.2.8 on 2021-11-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_steel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Steel',
            new_name='SteelMills',
        ),
    ]
