# Generated by Django 3.2.8 on 2021-11-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rename_steel_steelmills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steelmills',
            name='id',
        ),
        migrations.AddField(
            model_name='steelmills',
            name='Level',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
