# Generated by Django 3.2.8 on 2021-11-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_fighter_playerscore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fighter',
        ),
    ]
